import XCTest
@testable import WhoopProtocol

/// Cross-language parity for the WHOOP 5.0 (Maverick) decode path. Each fixture frame in
/// frames_5.json is a complete Maverick-wrapped frame ([0xAA][0x01][len][body][trailer]);
/// the Swift parseFrame() strips the wrapper internally and decodes the FLAT body against
/// the 5.0 schema, and the result MUST equal the Python golden produced by parse_body_5()
/// over the same body (run scripts/gen_golden.py to regenerate both files).
///
/// Parity holds BY CONSTRUCTION: golden_5.json is generated by the SAME Python decode of
/// the SAME bytes the Swift side decodes here. This test fails the build if the Maverick
/// strip or the body-absolute 5.0 offsets ported in 05-01 are wrong — the quality gate.
private struct GoldenEntry: Decodable {
    let type_name: String
    let seq: Int?
    let crc_ok: Bool?
    let cmd_name: String?
    let parsed: [String: ParsedValue]
}

private struct FrameEntry: Decodable {
    let hex: String
}

final class Parity5Tests: XCTestCase {
    private func resourceURL(_ name: String, _ ext: String) throws -> URL {
        let url = Bundle.module.url(forResource: name, withExtension: ext)
        return try XCTUnwrap(url, "missing test resource \(name).\(ext) — run scripts/gen_golden.py")
    }

    private func hexToBytes(_ s: String) -> [UInt8] {
        var out = [UInt8](); out.reserveCapacity(s.count / 2)
        var idx = s.startIndex
        while idx < s.endIndex {
            let next = s.index(idx, offsetBy: 2)
            out.append(UInt8(s[idx..<next], radix: 16)!)
            idx = next
        }
        return out
    }

    func testSwiftMatchesPython5Golden() throws {
        let framesData = try Data(contentsOf: resourceURL("frames_5", "json"))
        let goldenData = try Data(contentsOf: resourceURL("golden_5", "json"))
        let frames = try JSONDecoder().decode([FrameEntry].self, from: framesData)
        let golden = try JSONDecoder().decode([GoldenEntry].self, from: goldenData)

        XCTAssertEqual(frames.count, golden.count, "frames_5.json and golden_5.json length mismatch")
        XCTAssertGreaterThan(frames.count, 0, "no 5.0 parity frames loaded")

        for (i, frameEntry) in frames.enumerated() {
            let g = golden[i]
            let bytes = hexToBytes(frameEntry.hex)
            // Every fixture frame must be a Maverick wrapper so parseFrame() takes the 5.0 path.
            XCTAssertEqual(bytes.first, 0xAA, "frame #\(i) is not 0xAA-led")
            XCTAssertEqual(bytes.count > 1 ? bytes[1] : 0, 0x01, "frame #\(i) is not Maverick (version byte != 0x01)")

            let out = parseFrame(bytes)
            XCTAssertEqual(out.typeName, g.type_name, "type_name mismatch at #\(i)")
            XCTAssertEqual(out.seq, g.seq, "seq mismatch at #\(i) (\(g.type_name))")
            // crcOK is nil on the Maverick path (the flat body carries no inner CRC32).
            XCTAssertEqual(out.crcOK, g.crc_ok, "crc_ok mismatch at #\(i) (\(g.type_name))")
            XCTAssertNil(out.crcOK, "Maverick path must report crcOK == nil at #\(i)")
            XCTAssertEqual(out.cmdName, g.cmd_name, "cmd_name mismatch at #\(i) (\(g.type_name))")
            // The core no-drift contract: the parsed dict must match exactly, byte-for-byte.
            XCTAssertEqual(out.parsed, g.parsed,
                           "parsed mismatch at #\(i) (\(g.type_name))\n  swift: \(out.parsed)\n  python: \(g.parsed)")
        }
    }

    func testEveryCore5PacketTypeCovered() throws {
        let goldenData = try Data(contentsOf: resourceURL("golden_5", "json"))
        let golden = try JSONDecoder().decode([GoldenEntry].self, from: goldenData)
        let types = Set(golden.map { $0.type_name })
        for expected in ["REALTIME_DATA", "EVENT", "COMMAND_RESPONSE", "METADATA", "CONSOLE_LOGS"] {
            XCTAssertTrue(types.contains(expected), "5.0 parity fixture missing \(expected)")
        }
    }
}
