import XCTest
@testable import WhoopProtocol

/// Cross-language guarantee that Swift extractStreams == Python extract_streams over the
/// same fixture frames + refs. streams_golden.json is generated by scripts/gen_golden.py.
final class StreamsParityTests: XCTestCase {
    // MUST equal the constants in scripts/gen_golden.py.
    private let deviceClockRef = 31_538_447
    private let wallClockRef = 1_736_365_593

    // frames.json / streams_golden.json are the 4.0 fixture set; decode against the 4.0
    // schema (5.0 is the runtime default).
    override func setUp() { super.setUp(); overrideSchemaResource("whoop_protocol") }
    override func tearDown() { overrideSchemaResource(nil); super.tearDown() }

    private struct FrameEntry: Decodable { let hex: String }
    private struct HRGold: Decodable, Equatable { let ts: Int; let bpm: Int }
    private struct RRGold: Decodable, Equatable { let ts: Int; let rr_ms: Int }
    private struct BatGold: Decodable, Equatable { let ts: Int; let soc: Double?; let mv: Int?; let charging: Bool? }
    private struct EvGold: Decodable { let ts: Int; let kind: String; let payload: [String: ParsedValue] }
    private struct StreamsGold: Decodable {
        let hr: [HRGold]; let rr: [RRGold]; let events: [EvGold]; let battery: [BatGold]
    }

    private func resourceURL(_ name: String, _ ext: String) throws -> URL {
        try XCTUnwrap(Bundle.module.url(forResource: name, withExtension: ext),
                      "missing \(name).\(ext) — run scripts/gen_golden.py")
    }
    private func bytes(_ s: String) -> [UInt8] {
        var out = [UInt8](); out.reserveCapacity(s.count / 2)
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            out.append(UInt8(s[i..<j], radix: 16)!); i = j
        }
        return out
    }

    func testSwiftStreamsMatchPythonGolden() throws {
        let frames = try JSONDecoder().decode(
            [FrameEntry].self, from: Data(contentsOf: resourceURL("frames", "json")))
        let gold = try JSONDecoder().decode(
            StreamsGold.self, from: Data(contentsOf: resourceURL("streams_golden", "json")))

        let parsed = frames.map { parseFrame(bytes($0.hex)) }
        let s = extractStreams(parsed, deviceClockRef: deviceClockRef, wallClockRef: wallClockRef)

        XCTAssertEqual(s.hr, gold.hr.map { HRSample(ts: $0.ts, bpm: $0.bpm) })
        XCTAssertEqual(s.rr, gold.rr.map { RRInterval(ts: $0.ts, rrMs: $0.rr_ms) })
        XCTAssertEqual(s.battery, gold.battery.map { BatterySample(ts: $0.ts, soc: $0.soc, mv: $0.mv, charging: $0.charging) })
        XCTAssertEqual(s.events.count, gold.events.count, "event count mismatch")
        for (i, g) in gold.events.enumerated() {
            XCTAssertEqual(s.events[i].ts, g.ts, "event ts mismatch #\(i)")
            XCTAssertEqual(s.events[i].kind, g.kind, "event kind mismatch #\(i)")
            XCTAssertEqual(s.events[i].payload, g.payload, "event payload mismatch #\(i) (\(g.kind))")
        }
        // Sanity: the fixture must actually exercise the stream types.
        XCTAssertGreaterThan(s.hr.count, 0)
        XCTAssertGreaterThan(s.events.count, 0)
        XCTAssertGreaterThan(s.battery.count, 0)
    }
}
